#!/bin/bash

DIR='~/.dotfiles'

# ===== Sources

touch ~/.profile
touch ~/.bashrc

echo "source $DIR/.profile" >> ~/.profile
echo "source ~/.profile" >> ~/.bashrc
echo "source $DIR/.tmux.conf" >> ~/.tmux.conf;

mkdir -p ~/.config/nvim
echo "source $DIR/nvim/init.vim" >> ~/.config/nvim/init.vim

# ===== Version Managers

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash

# ===== Neovim

curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

nvim +'PlugInstall --sync' +qa
