#!/bin/bash

DIR='~/.dotfiles'

touch ~/.profile
touch ~/.bashrc

echo "source ~/.dotfiles/.profile" >> ~/.profile
echo "source ~/.profile" >> ~/.bashrc

# ===== Version Managers

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash

# ===== Sources

sources=(tmux.conf);

# sources

for i in "${sources[@]}"; do
  if [ -e ~/.$i ]
  then
    echo "error file .$i exists";
  else
    echo "writing .$i";
    echo "source ${DIR}/.$i" >> ~/.$i;
  fi
done

# symlinks
declare -A symlinks

symlinks['alacritty.yml']='~/.config/alacritty'
symlinks['nvim/init.vim']='~/.config'

echo $(/bin/bash --version)
for symlink in "${!symlinks[@]}"; do
  if [ -e ~/.$symlink ]
  then
    echo "error file .$symlink exists";
  else
    echo "symlinking ${symlinks[$symlink]}/.$symlink";
    mkdir -p "${symlinks[$symlink]}"
    ln -s ${DIR}/.$symlink ${symlinks[$symlink]}/.$symlink;
  fi
done

